#!/bin/bash
chown -R $(whoami) $(brew --prefix);
gem update --system;
gem update;
brew update && brew upgrade && brew cleanup && brew prune && brew doctor;
brew cask cleanup;
npm update -g && npm cache clean;
pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip install -U;
pip install --upgrade pip;
apm upgrade -c false;
cpan-outdated -p | cpanm;
exit;
