#!/bin/bash
chown -R $(whoami) $(brew --prefix) &>/dev/null;
gem update --system;
gem update;
brew update && brew upgrade && brew cleanup && brew prune && brew doctor;
brew cask cleanup;
npm update -g && npm cache verify;
pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip3 install -U;
pip3 install --upgrade pip;
apm upgrade -c false;
cpan-outdated -p | cpanm;
exit;
